### ISSUE TITLE
Fuse mode in docker container errors on Mac OS Big Sur

### ISSUE THREAD

**Issue by chmoder** [GoogleCloudPlatform/cloudsql-proxy#1007]
## Bug Description

Following this [working Linux solution](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/444#issuecomment-717600896) for running google cloud_sql_proxy via docker containers on Mac OS Big Sur 11.6 the following error occurs:  

`docker: Error response from daemon: path /cloudsql is mounted on /cloudsql but it is not a shared mount.`

## Example code (or command)

n/a

#### Error:
```
docker: Error response from daemon: path /cloudsql is mounted on /cloudsql but it is not a shared mount.
```
#### docker events:
```
2021-11-04T14:21:39.610001501-05:00 container create 127263a29ad00daecb8694d7406bea9b74e9ede9a61dd5c1b7f7cbfe316e265b (image=proxy-buster-dev, name=proxy)
2021-11-04T14:21:39.614097636-05:00 container attach 127263a29ad00daecb8694d7406bea9b74e9ede9a61dd5c1b7f7cbfe316e265b (image=proxy-buster-dev, name=proxy)
2021-11-04T14:21:39.664471533-05:00 network connect 97fc4b627439e94b9528666783786304f2a2038efe44ae577d362c05b81b7e12 (container=127263a29ad00daecb8694d7406bea9b74e9ede9a61dd5c1b7f7cbfe316e265b, name=bridge, type=bridge)
2021-11-04T14:21:39.706083431-05:00 network disconnect 97fc4b627439e94b9528666783786304f2a2038efe44ae577d362c05b81b7e12 (container=127263a29ad00daecb8694d7406bea9b74e9ede9a61dd5c1b7f7cbfe316e265b, name=bridge, type=bridge)
2021-11-04T14:21:39.713146656-05:00 container destroy 127263a29ad00daecb8694d7406bea9b74e9ede9a61dd5c1b7f7cbfe316e265b (image=proxy-buster-dev, name=proxy)

```

## How to reproduce

We have reproduced this with the example from the previously referenced issue, and also with docker compose.  To keep things uniform, below is the technique we used to produce this error.

```
git clone https://github.com/GoogleCloudPlatform/cloudsql-proxy.git
```

```
docker build -f Dockerfile.buster --tag proxy-buster-dev . 
```

```shell
docker run -it --rm --name proxy --user=root \
  --mount type=bind,source=<path-to-cred-file>,target=/config/credentials.json \
  --mount type=bind,source=/cloudsql,target=/cloudsql \
  --mount type=bind,source=/tmp/cloudsql,target=/tmp/cloudsql \
  --device /dev/fuse \
  --privileged \
  proxy-buster-dev \
  /cloud_sql_proxy -fuse -fuse_tmp /tmp/cloudsql -dir /cloudsql -credential_file=/config/credentials.json
```

## Environment

1. OS type and version: Mac OS Big Sur 11.6
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.27.1
3. Docker desktop 4.1.1
4. Docker engine 20.10.8

**Comment by chmoder** [comment]
Adding the docker desktop "about" window with all the used versions:
![image](https://user-images.githubusercontent.com/82629/140410867-f6135551-2bee-4fb6-806e-b9a9bba0d4c5.png)

**Comment by enocom** [comment]
Thanks @chmoder for the report. I'll take a look at this.

**Comment by enocom** [comment]
Have you tried this on v1.26.0? We switched the backing FUSE library in v1.27.0 and so I'm wondering if this is a problem with the new version.

**Comment by enocom** [comment]
I tried this on my Intel Mac with v1.26.0 and see it's not working there. The FUSE mount succeeds inside the container, but the host directory doesn't mount.

**Comment by enocom** [comment]
After some further research, I found a couple of things.

1. The full command should be:
```
docker run -it --rm --name proxy --user=root \
  --mount type=bind,source=<path-to-cred-file>,target=/config/credentials.json \
  --mount type=bind,source=/cloudsql,target=/cloudsql,bind-propagation=rshared \
  --mount type=bind,source=/tmp/cloudsql,target=/tmp/cloudsql,bind-propagation=rshared \
  --device /dev/fuse \
  --privileged \
  proxy-buster-dev \
  /cloud_sql_proxy -fuse -fuse_tmp /tmp/cloudsql -dir /cloudsql -credential_file=/config/credentials.json
```

Note the `bind-propagation` addition.

2. You'll need to enable File Sharing for both the `/tmp` dir and the `/cloudsql` dir. There's a screenshot here with a fairly recent version of Docker desktop: https://stackoverflow.com/a/68495984/927514

As a side note, I've tried the same on a Linux machine (replacing the Docker desktop step with `mount --make-shared /` and do see the directory mounted, but cannot connect to my database using `psql`, both with v1.26.0 and v1.27.0. I suspect this is caused by a change in Docker.

**Comment by chmoder** [comment]
Thanks for the help, I would guess you are having trouble connecting because of some IAM permissions issue?  Beconse on a GCE instance running _ubuntu-2004-focal-v20200423_  we were quickly able to use the following docker compose yml to connect to a cloud SQL instance.  However we still can't seem to get Mac OS to run it.  Have you tried using non-privileged directories on the host?  `/Users/<user>/cloudsql` for example?

#### docker-compose.yml
```
version: '3'
services:
  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.27.0-buster
    command: /cloud_sql_proxy --dir=/cloudsql -credential_file=/credentials.json -fuse -fuse_tmp /tmp/cloudsql -verbose
    user: root
    privileged: true
    ports:
    - "3306:3306"
    volumes:
      - type: "bind"
        source: "/home/tcross/csg_env/credentials.json"
        target: "/credentials.json"
      - type: "bind"
        source: "/cloudsql"
        target: "/cloudsql"
        bind:
          propagation: rshared
      - type: "bind"
        source: "/tmp/cloudsql"
        target: "/tmp/cloudsql"
        bind:
          propagation: rshared
```

#### docker run:
```
tcross@<redacted>:~/csg_env$ docker compose up
[+] Running 1/0
 ⠿ Container cloudsql-proxy  Created                                                                          0.0s
Attaching to cloudsql-proxy
cloudsql-proxy  | 2021/11/05 12:49:08 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
cloudsql-proxy  | 2021/11/05 12:49:08 using credential file for authentication; email=<redacted>@appspot.gserviceaccount.com
cloudsql-proxy  | 2021/11/05 12:49:08 Ready for new connections
cloudsql-proxy  | 2021/11/05 12:49:08 Generated RSA key in 230.402363ms
cloudsql-proxy  | 2021/11/05 12:49:13 refreshing ephemeral certificate for instance<redacted>:us-central1:django-v2
cloudsql-proxy  | 2021/11/05 12:49:13 Scheduling refresh of ephemeral certificate in 23h54m59.182745704
cloudsql-proxy  | 2021/11/05 12:51:57 Client closed local connection on /tmp/cloudsql/<redacted>:us-central1:django-v2
```

#### mysql connection:
```
mysql -S /cloudsql/<redaccted>:us-central1:django-v2 -p<password> -u <user>
```

**Comment by enocom** [comment]
OK. Thanks for the docker-compose file. I've tried on a fresh GCE VM as well and can confirm that it does work. I'll try the same on my mac and report back.

Given how tricky it is to get this working, whatever we find here, it seems like adding this somewhere in our docs (rather than in an old issue) would be useful.

**Comment by enocom** [comment]
When trying this same experiment on my Intel Mac with the latest Docker Desktop, I'm getting this (note I'm mounting on `/tmp/cloudsql` instead of `/cloudsql`):

```
ERROR: for cloudsql-proxy  Cannot start service cloudsql-proxy: path /tmp/cloudsql is mounted on /tmp but it is not a shared mount
```

Which is an open issue (https://github.com/docker/for-mac/issues/3431).

How are you getting around this?

**Comment by chmoder** [comment]
[This](https://github.com/docker/for-mac/issues/3431#issuecomment-545267759) post does enable us to set up the bind mounts with propagation.  However, I haven't been able to connect to the MySQL server from Mac OS yet.  I logged into the container and was able to connect and create files on the host and see them in the container.  Maybe at this point you can test connecting to cloud_sql_proxy? 

Error:
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/cloudsql/<redacted>:us-central1:django-v2' (61)
```

./shared-mount/Dockerfile
```
FROM alpine:latest
ENV  MOUNTDIR=/tmp
CMD  nsenter -t $(pgrep docker-init) -m -- mount --verbose --make-shared ${MOUNTDIR}
```

docker-compose.yml
```yml
version: '3.7'

services:
  shared-mount:
    build:
      context: ./shared-mount
    privileged: true
    stdin_open: true
    tty: true
    pid: "host"
    environment:
      - MOUNTDIR=/tmp
  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.27.0-buster
    command: /cloud_sql_proxy --dir=/cloudsql -credential_file=/credentials.json -fuse -fuse_tmp /tmp/cloudsql -verbose
    user: root
    privileged: true
    depends_on:
        - shared-mount
    ports:
    - "3306:3306"
    volumes:
      - type: "bind"
        source: "/Users/tcross/development/proxy/credentials.json"
        target: "/credentials.json"
      - type: "bind"
        source: "/tmp/cloudsql"
        target: "/cloudsql"
        bind:
          propagation: rshared
      - type: "bind"
        source: "/tmp/cloudsql-tmp"
        target: "/tmp/cloudsql"
        bind:
          propagation: rshared
```
