### ISSUE TITLE
Support Workload Identity Federation

### ISSUE THREAD

**Issue by j0hnsmith** [GoogleCloudPlatform/cloudsql-proxy#1096]
## Feature Description
I tried using this in a github action that uses WIF to run as a service account, I got an auth error. I then used [export_default_credentials](https://github.com/google-github-actions/setup-gcloud#authentication-inputs) and it worked (no other changes).

## Additional Context
As suggested in https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/1006#issuecomment-985001107, I'm 99% sure that if you update the deps that provide the auth functionality to this tool to the latest version, auth via WIF will work.

**Comment by enocom** [comment]
So here's what I did. Adding all the steps in case others want to try the same.

1. Created a pool:

```
gcloud iam workload-identity-pools create "my-pool" \
  --location="global" \
  --display-name="Demo pool"
```

2. Created an OIDC provider for GitHub:

```
gcloud iam workload-identity-pools providers create-oidc "my-provider" \
  --location="global" \
  --workload-identity-pool="my-pool" \
  --display-name="Demo provider" \
  --attribute-mapping="google.subject=assertion.sub,attribute.actor=assertion.actor,attribute.aud=assertion.aud" \
  --issuer-uri="https://token.actions.githubusercontent.com"
```

3. Added an IAM binding to allow the pool to assume the SA identity:

```
gcloud iam service-accounts \
    add-iam-policy-binding "sa@<project-id>.iam.gserviceaccount.com" \
    --role="roles/iam.workloadIdentityUser" \
    --member="principalSet://iam.googleapis.com/projects/<project-number>/locations/global/workloadIdentityPools/my-pool/attribute.repository/<github-org>/<github-repo>"
```
And then here's my action.

```
name: check
on: [push]

jobs:
  check:
    name: "check wif"
    runs-on: "ubuntu-latest"
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v2'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/84977719781/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'workload-identity@enocom-experiments-304623.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: "print env"
      run: "env | sort"

   - name: start proxy                                                                                                        
      run: |                                                                                                                   
        wget "https://storage.googleapis.com/cloudsql-proxy/v1.28.1/cloud_sql_proxy.linux.amd64" -O cloud_sql_proxy            
        chmod +x ./cloud_sql_proxy                                                                                             
        ./cloud_sql_proxy -instances=enocom-experiments-304623:us-central1:pg=tcp:5432 &                                       
        echo $! > pid.file                                                                                                     
        sleep 60                                                                                                               
        kill $(cat pid.file)
```

From the output, I can see that `GOOGLE_APPLICATION_CREDENTIALS` is correctly populated and that it works (`gcloud info` reports correctly). Further, the proxy will use a provided 1) credentials file, 2) token, and then 3) try to use `GOOGLE_APPLICATION_CREDENTIALS` ([source](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/main/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L361-L382)).

The proxy then fails with this error:

```
2022/02/09 21:21:24 current FDs rlimit set to 65536, wanted limit is 8500. Nothing to do here.
2022/02/09 21:21:24 using credential file for authentication; path="/home/runner/work/_temp/8a2ab4ef9b265c5ad0042ac8"
2022/02/09 21:21:25 errors parsing config:
	Get "https://sqladmin.googleapis.com/sql/v1beta4/projects/enocom-experiments-304623/instances/us-central1~pg/connectSettings?alt=json&prettyPrint=false": oauth2/google: status code 403: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

This looks like an OAuth2 scope problem, as the proxy is picking up the correct `GOOGLE_APPLICATION_CREDENTIALS`.
