### ISSUE TITLE
Readiness and liveness probes in Kubernetes

### ISSUE THREAD

**Issue by wayneashleyberry** [GoogleCloudPlatform/cloudsql-proxy#119]
I'm struggling to setup a health check for the proxy container on Kubernetes. Some documentation or guidance around this would be great. We're having to delete pods quite regularly due to an app not being able to connect.

Tried [defining a tcp liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-tcp-liveness-probe) which didn't quite do the trick.

**Comment by AthenaShi** [comment]
So far we don't expose such thing unfortunately...

As a work around you can check by run cmd: 
netcat -U /cloudsql/$INSTANCE_CONNECTION_STRING

As for the "an app not being able to connect" issue, if you think it might due to cloud sql proxy, please send an email with following information to cloud-sql@google.com so I may be able to help out looking at some internal data.

- with a link to this page.
- describe the issue you have.
- the full name of your cloud sql instance.
- the command your run
- the full logs

**Comment by rosskevin** [comment]
When trying to [deploy as recommended in kubernetes](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/Kubernetes.md) with spinnaker, it seems the lack of the probe causes the `highlander` strategy to tear down the node.

I'll try the `netcat`, but it would be convenient if there was a typical set of endpoints without having the INSTANCE_CONNECTION_STRING in more than one place.

**Comment by rosskevin** [comment]
`netcat` is not available on the stock image, so this:

```yaml
livenessProbe:
  exec:
    command: ["netcat", "-U", "/cloudsql/coverbid:us-central1:db=tcp:3306"]
  initialDelaySeconds: 5
  timeoutSeconds: 10
```

fails with 

```
Liveness probe failed: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"netcat\": executable file not found in $PATH" 
```

**Comment by rosskevin** [comment]
I misunderstood netcat's location and options on the image.

I attempted the following:

```yaml
livenessProbe:
  exec:
    command: ["nc", "/cloudsql/foo:us-central1:db=tcp:3306"]
  initialDelaySeconds: 5
  timeoutSeconds: 3
```

and it failed with:

```
Liveness probe failed: nc: bad address '/cloudsql/foo:us-central1:db=tcp:3306'
```

Has anyone else gotten `nc` to work as a probe?

**Comment by AthenaShi** [comment]
Would you please try:

```yaml
livenessProbe:
  exec:
    command: ["nc", "127.0.0.1", "3306"]
  ...
```

The command I pasted before (netcat -U /cloudsql/$INSTANCE_CONNECTION_STRING) was for unix domain socket.

**Comment by rosskevin** [comment]
Thanks @AthenaShi, that does report success.

**Comment by AthenaShi** [comment]
Seems like there's no problem left for this thread.  Close it.

**Comment by hews** [comment]
FYI I actually needed to run it slightly differently; that is I needed to run `nc` in [zero-I/O (scan) mode](https://www.commandlinux.com/man-page/man1/nc.1.html):

```yaml
livenessProbe:
  exec:
    command: ["nc", "-z", "127.0.0.1", "3306"]
  ...
```
