### ISSUE TITLE
Crashing node on kubernetes upon first connection

### ISSUE THREAD

**Issue by rosskevin** [GoogleCloudPlatform/cloudsql-proxy#122]
I had `cloud_sql_proxy` prototyped as a sidecar, then as I was moving to spinnaker noticed that jobs cannot be configured with multiple containers.

I then bumped into [](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/Kubernetes.md) in this repo and decided to break it out on it's own.  I brought my prototype config, added it to a spinnaker pipeline and it produced the following:

```yaml
---
apiVersion: "extensions/v1beta1"
kind: "ReplicaSet"
metadata:
  finalizers: []
  labels:
    app: "foo"
    cluster: "foo-prod-sqlproxy"
    foo-prod-sqlproxy-v000: "true"
    detail: "sqlproxy"
    load-balancer-foo-prod-db: "true"
    replication-controller: "foo-prod-sqlproxy-v000"
    stack: "prod"
    version: "0"
  name: "foo-prod-sqlproxy-v000"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  selector:
    matchExpressions: []
    matchLabels:
      app: "foo"
      cluster: "foo-prod-sqlproxy"
      foo-prod-sqlproxy-v000: "true"
      detail: "sqlproxy"
      replication-controller: "foo-prod-sqlproxy-v000"
      stack: "prod"
      version: "0"
  template:
    metadata:
      finalizers: []
      labels:
        app: "foo"
        cluster: "foo-prod-sqlproxy"
        foo-prod-sqlproxy-v000: "true"
        detail: "sqlproxy"
        load-balancer-foo-prod-db: "true"
        replication-controller: "foo-prod-sqlproxy-v000"
        stack: "prod"
        version: "0"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command:
        - "/cloud_sql_proxy"
        - "--dir=/cloudsql"
        - "-instances=foo:us-central1:db=tcp:3306"
        - "-credential_file=/secrets/cloudsql/credentials.json"
        env: []
        image: "gcr.io/cloudsql-docker/gce-proxy:1.11"
        imagePullPolicy: "IfNotPresent"
        name: "cloudsql-docker-gce-proxy"
        ports:
        - containerPort: 3306
          name: "db"
          protocol: "TCP"
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        volumeMounts:
        - mountPath: "/secrets/cloudsql"
          name: "cloudsql-instance-credentials"
          readOnly: true
        - mountPath: "/etc/ssl/certs"
          name: "ssl-certs"
        - mountPath: "/cloudsql"
          name: "cloudsql"
        terminationMessagePolicy: "File"
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "docker-account"
      - name: "gcr-account"
      restartPolicy: "Always"
      securityContext:
        supplementalGroups: []
      terminationGracePeriodSeconds: 30
      volumes:
      - name: "cloudsql-instance-credentials"
        secret:
          defaultMode: 420
          items: []
          secretName: "cloudsql-instance-credentials"
      - hostPath:
          path: "/etc/ssl/certs"
        name: "ssl-certs"
      - emptyDir: {}
        name: "cloudsql"
      schedulerName: "default-scheduler"
status:
  availableReplicas: 1
  conditions: []
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
```
I also upgraded the service account role from `roles/cloudsql.client` as recommended by the google docs, to `roles/editor` as recommended by the doc in this repo.

The proxy starts up:
```
E  2017/10/07 22:12:18 Ready for new connections
E  2017/10/07 22:18:12 using credential file for authentication; email=cloud-sql-client@foo.iam.gserviceaccount.com
E  2017/10/07 22:18:12 Listening on 127.0.0.1:3306 for foo:us-central1:db
```

```
❯❯❯ kubectl get pods
NAME                                READY     STATUS    RESTARTS   AGE
foo-prod-sqlproxy-v000-537g8   1/1       Running   0          18m
```

Upon the first connection, I watch pods status and immediately it terminates:

```
❯❯❯ kubectl get pods
NAME                                 READY     STATUS        RESTARTS   AGE
foo-frontend-2250245535-5xq8m   0/1       Running       0          1s
foo-prod-sqlproxy-v001-jw3bs    0/1       Terminating   0          8m
```

The same thing happens if I try to add an internal liveness probe (as noted in #119), though I now suspect this is isolated to my config.

I cannot spot the reason for the crash, and there are no errors in the logs.  Where should I look next?

**Comment by rosskevin** [comment]
Here is a more refined test case taken from the doc referenced above using a liveness probe (#119) that self crashes:

```
❯❯❯ kubectl get pods
NAME                            READY     STATUS    RESTARTS   AGE
cloudsqlproxy-109958711-ks4bf   1/1       Running   5          2m
```

## deployment

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudsqlproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudsqlproxy
    spec:
      containers:
      - image: gcr.io/cloudsql-docker/gce-proxy:1.09
        name: cloudsqlproxy
        command: "/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=foo:us-central1:db=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        ports:
        - name: port-db
          containerPort: 3306

        livenessProbe:
          exec:
            command: ["netcat", "-U", "/cloudsql/foo:us-central1:db=tcp:3306"]
          initialDelaySeconds: 5
          timeoutSeconds: 10

        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
```
## service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: cloudsqlproxy-service
spec:
  ports:
  - port: 3306
    targetPort: port-db
  selector:
    app: cloudsqlproxy
```
