### ISSUE TITLE
Cannot connect to mysql - Kubernetes cluster

### ISSUE THREAD

**Issue by rosskevin** [GoogleCloudPlatform/cloudsql-proxy#124]
I'm following this doc: https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/Kubernetes.md

I've also tried several other example variations, but I'm back here after two full days of fighting, for the love of god someone point out my error.

I have definitively ruled out credentials problems (and for reassurance the service account has the `Editor` role).  Simultaneously, I have:
- my app running with sidecar that connects
- my app running trying to connect through a sqlproxy service+deployment that fails

I need to get away from the sidecar to move forward.

I ssh into my app pod and attempt a direct `mysql -h` connection, and I get an immediate failure of:
```
ERROR 2003 (HY000): Can't connect to MySQL server on 'sqlproxy-service-db' (111)`
```

The attempt doesn't hang.  I ran a ping on `sqlproxy-service-db` and the ip matched the service listed by `kubectl get services`.

Here's the configs, they start and seem 100% fine to me:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: sqlproxy-service-db
spec:
  ports:
  - port: 3306
    targetPort: port-db
  selector:
    app: cloudsqlproxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudsqlproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudsqlproxy
    spec:
      containers:
       # Make sure to specify image tag in production
       # Check out the newest version in release page
       # https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
      - image: gcr.io/cloudsql-docker/gce-proxy:latest
       # 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
        imagePullPolicy: Always
        name: cloudsqlproxy
        command:
        - /cloud_sql_proxy
        - -dir=/cloudsql
        - -instances=foo:us-central1:db=tcp:3306
        - -credential_file=/credentials/credentials.json
        ports:
        - name: port-db
          containerPort: 3306
        volumeMounts:
        - mountPath: /credentials
          name: cloudsql-instance-credentials
        - mountPath: /cloudsql
          name: cloudsql
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir:
```

^^^ this is my last attempt trying to get it absolutely as close as possible to the doc.

What could I be missing here?  Sidecar works, ^^^ setup doesn't.
