### ISSUE TITLE
Cloud SQL Proxy logs show up as severity: ERROR in Stackdriver logging when using Kubernetes

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/cloudsql-proxy#138]
This configuration:

```
      - name: sqlproxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        volumeMounts:
        - name: cloudsql
          mountPath: /cloudsql
        - name: sql-secret-volume
          mountPath: /secret/
          readOnly: true
        command: ["/cloud_sql_proxy", "-dir=/cloudsql", "-credential_file=/secret/file.json", "-instances=myproject:myinstance=tcp:3306"]
```

Leads to logs that have `severity: ERROR` in Stackdriver logging.

Something like this:

```
severity:  "ERROR"  
 textPayload:  "2018/01/06 21:10:33 Listening on 127.0.0.1:3306...
```

It is kind of disrupting to see a long stream of non-error logs when searching for actual errors.

Does anyone know a way to get proper log levels from cloud sql proxy docker image?

Thanks!
