### ISSUE TITLE
Regular increase of disk usage

### ISSUE THREAD

**Issue by idubnori** [GoogleCloudPlatform/cloudsql-proxy#213]
`cloudsql-proxy` seems to leak disk on the pod resource graph. 
Is it expected behavior or, any wrong settings?

It is using to connect to `Cloud SQL for PostgreSQL`.

![cloudsql-proxy-disk-leak](https://user-images.githubusercontent.com/22805312/46056954-33994680-c18e-11e8-9916-c62cc532185e.png)

**Comment by kurtisvg** [comment]
Hi @idubnori,

Could you post the settings you are using? Is your application correctly closing connections after they are used?

**Comment by Carrotman42** [comment]
I don't think the cloudsql-proxy uses the disk much at all, so this is a
little weird. Have you configured something in the pod to write logs to a
local file or something?

**Comment by idubnori** [comment]
Hi @kurtisvg @Carrotman42,

Thank you for your advices.

The configuration is almost based on GKE tutorial.
My container app stacks are `ASP.NET Core` + `EF Core` + `npgsql`. And Active connection count leak did not observe on `Cloud SQL for PostgreSQL` resource graph.

I belive my container does not output any local files or something to the container side, but the purple graph(my container) has the one cliff of disk usage increment. I will check it again...

The normal behavior is that `cloudsql-proxy` disk usage graph should be perfect flat?

**Comment by idubnori** [comment]
```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo-api
  labels:
    app: foo-api
spec:
  template:
    metadata:
      labels:
        app: foo-api
    spec:
      containers:
        - name: foo-api
          image: asia.gcr.io/foo-project-id/foo.api:latest
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 1500m
              memory: 256Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # The following environment variables will contain the database host,
          # user and password to connect to the PostgreSQL instance.
          env:
            # [START cloudsql_secrets]
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            # [END cloudsql_secrets]
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__FooDatabase
              value: "Host=127.0.0.1;Port=5432;Username=$(POSTGRES_DB_USER);Password=$(POSTGRES_DB_PASSWORD);Database=Foo"
          readinessProbe:
            httpGet:
                path: /hc
                port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          foo: ["/cloud_sql_proxy",
                    "-instances=foo-project-id:asia-northeast1:foo-cloudsql-1=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          resources:
            requests:
              cpu: 10m
              memory: 8Mi
            limits:
              cpu: 100m
              memory: 32Mi
          # [START cloudsql_security_context]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          # [END cloudsql_security_context]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes
```
