### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sharpn** [GoogleCloudPlatform/cloudsql-proxy#257]
We have started recently receiving a-lot of the above error from out sql proxies running in GKE. It seems to happen until the application is restarted.

Is there anything we can do to rectify with this issue?

**Comment by kurtisvg** [comment]
Hi @sharpn,

Can you please provide more information - perhaps a snippet from the logs when you encounter this error? Are you connecting via a VPC network?

**Comment by wedi** [comment]
This could be related:
From time to time I am seeing a log message like the following and other containers cannot connect anymore. I can resolve this by manually restarting the proxy container. Running on GCP.

```
2019/03/13 18:48:24 errors parsing config:
     Get https://www.googleapis.com/sql/v1beta4/projects/<project-id>/instances/<instance-name>?alt=json&prettyPrint=false: x509: certificate is valid for <some-hostname.com>, not www.googleapis.com
```

I really wonder where this comes from as I do not configure any hostname. 🤔

composer.yml
```YAML
services:
    mysql:
      image: gcr.io/cloudsql-docker/gce-proxy:1.12
      command: /cloud_sql_proxy -dir=/var/run/mysqld/ -instances=${GCLOUD_SQL_INSTANCE_CONNECTION_NAME}
      volumes:
        - mysql-socket-vol-1:/var/run/mysqld/
```
