### ISSUE TITLE
Can't use default postgresql Unix Socket directory

### ISSUE THREAD

**Issue by gustavovalverde** [GoogleCloudPlatform/cloudsql-proxy#301]
On GKE, with the following config:

```yaml
- name: cloudsql-proxy
  image: gcr.io/cloudsql-docker/gce-proxy:1.14
  command: ["/cloud_sql_proxy",
            "-instances=<INSTANCE_CONNECTION_NAME>=unix:/var/run/postgresql",
            "-credential_file=/secrets/cloudsql/credentials.json"]
  securityContext:
    runAsUser: 2  # non-root user
    allowPrivilegeEscalation: false
  volumeMounts:
    - name: cloudsql-instance-credentials
      mountPath: /secrets/cloudsql
      readOnly: true
    - name: cloudsql  
      mountPath: /var/run/postgresql
```

This causes the following error on the container: 
```
errors parsing config:
invalid "<INSTANCE_CONNECTION_NAME>=unix:/var/run/postgresql": unrecognized network unix
```

**Comment by kurtisvg** [comment]
Closing since v.1.15 is released.

**Comment by gustavovalverde** [comment]
Hi @kurtisvg. An update on this one; after using v1.15

I, first, updated my deployment using TCP (the same method I've been using the past month). I just changed the image version from 1.14 to 1.15, nothing else changed.

After doing this my deployment failed completely as it wasn't able to get a connection to the database; and this error arises again: 

`Get https://www.googleapis.com/sql/v1beta4/projects/<instance-name>?alt=json&prettyPrint=false: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: dial tcp 74.125.141.95:443: connect: connection refused`

Going back to 1.14 fixes the connection. There's something fishy in 1.15.

**Comment by kurtisvg** [comment]
Can you post your configuration for the sidecar? Are you able to test on a cluster w/o Istio to rule out if that's a problem or not?

**Comment by kurtisvg** [comment]
I tried this again, this time with the official `gcr.io/cloudsql-docker/gce-proxy` version. I started with 1.14, then moved to 1.15 and am unable to replicate this issue. 

Given the error (`dial tcp 74.125.141.95:443: connect: connection refused`), it seems likely this is a networking issue. Can you try to reach `74.125.141.95` from the container? 

Here's my yaml: 
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tabs-vs-spaces
  labels:
    app: tabs-vs-spaces
spec:
  template:
    metadata:
      labels:
        app: tabs-vs-spaces
    spec:
      containers:
        - name: tabs-vs-spaces
          image: gcr.io/<my-project>/tabs-vs-spaces
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: csql-secrets
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: csql-secrets
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: csql-secrets
                  key: dbname
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.15
          # Replace <INSTANCE_CONNECTION_NAME> with your instances connection name!
          command: ["/cloud_sql_proxy",
                    "-instances=<my-project>:<my-region>:<my-instance>=tcp:5432",
                    "-credential_file=/secrets/cloudsql/proxy-acct.json"]
          volumeMounts:
            - name: my-secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: my-secrets-volume
          secret:
            secretName: csql-proxy-acct

```

**Comment by gustavovalverde** [comment]
Hi @kurtisvg after a bunch of testing I managed to identify that v1.15 actually creates the issue with istio. No matter if it's using TCP or Unix Sockets; if there's a sidecar with the deployment it will always get: 

`Get https://www.googleapis.com/sql/v1beta4/projects/<instance-name>?alt=json&prettyPrint=false: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: dial tcp 74.125.141.95:443: connect: connection refused`

This happens with istio 1.2.X installed with helm using the defaults + SDS gateway.

**Comment by kurtisvg** [comment]
@gustavovalverde I asked some folks with more Isitio experience than myself, and says this likely due to outbound access being disabled. They recommended to trying using ServiceEntry objects similar to these:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - www.googleapis.com
  - oauth2.googleapis.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
```

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloudsql
spec:
  hosts:
  - <instance_ip>
  addresses:
  -  <instance_ip>/32
  ports:
  - name: tcp
    number: 3307
    protocol: tcp
  location: MESH_EXTERNAL
```
