### ISSUE TITLE
CloudSQL Proxy slow with PHP when got high traffic.

### ISSUE THREAD

**Issue by ALTELMA** [GoogleCloudPlatform/cloudsql-proxy#324]
I try to configure out for a slow connection from PHP to CloudSQL via Proxy, running on GKE.
So I think it causes from PHP, but I saw some logs such as

New connection for "xxxxxx" and wait for a while around 4-5 seconds the connection is closed.
However, I don't want to blame CloudSQL, but Anyone can confirm the root cause not come from it.

FYI, I already ask this question at Google Forum, but no one can help me :(

**Comment by kurtisvg** [comment]
Hi @ALTELMA - Can you please clarify by what you mean by "slow connection"? 

If you believe the issue is related to the proxy, it helps to have some comparison with/without or at least steps to reproduce.

**Comment by ALTELMA** [comment]
Sorry for a little information. So I have migrated out the application from the old one that maintenance by another company to a new infrastructure with a new change such as Cloud SQL etc.

After we finished the migration look like a performance dropped. I try to do a load test using WRK compare between the old version and the new version of infra.

Test with a URL to get user profile by id:
**OLD:**
Total Request: 9000 - 9500
RPS: around 79

**New:**
Total Request: 210
RPS: 34

Now I am trying to find what is the bottleneck?
For another question, I wonder about k8s config between the app and CloudSQL container should relate to this issue?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: asia.gcr.io/rabbit-digital/app-image:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: cloud-storage-volume
              mountPath: /var/www/storage/keys
              readOnly: true
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: db-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "3G"
              cpu: "100m"

        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          command:
            [
              "/cloud_sql_proxy",
              "-instances=<project-name>:<region>:<instance-connection-name>-1=tcp:5432",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "3G"
              cpu: "100m"
      volumes:
        - name: cloudsql-secrets-volume
          secret:
            secretName: cloudsql-instance-credentials
```
What is the best practice for this? Should be create a new service for CloudSQL or not?
