### ISSUE TITLE
Upgrading from 1.14 to 1.16 causes authError, Message: Invalid Credentials

### ISSUE THREAD

**Issue by carlos-cubas** [GoogleCloudPlatform/cloudsql-proxy#339]
Recently I upgraded cloud-sql-proxy to 1.16 and spent most of my day figuring out what portion of my configuration i had screwed up.  Rolling back to 1.14 resolves the problem...  Here is what is shown in the logs:

``` sh
E 2019-12-30T19:01:10.104576468Z Reason: authError, Message: Invalid Credentials
E 2019-12-30T19:01:10.104570780Z More details:
E 2019-12-30T19:01:10.104557726Z 	googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
E 2019-12-30T19:01:10.104518343Z 2019/12/30 19:01:10 errors parsing config:
 ```

Perhaps there's some config parsing change introduced?
This issue appears similar to #301

**Comment by kurtisvg** [comment]
Hi @carlos-cubas - Can you provide more info so we can try to replicate? What does your config look like and what scenario are you using the proxy in?

**Comment by carlos-cubas** [comment]
I have the proxy deployed as a sidecar in a pod that hosts a nodejs api server within GKE.  I use the docker-image gce-proxy:1.16.

Changing it to 1.14 fixes the above error.

my config looks as follows:

``` yaml
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: example-server
  labels:
    app: example
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: example
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: example
        tier: api
    spec:
      containers:
      - name: example
        image: gcr.io/example-dev/example-server:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        - name: DB
          valueFrom:
            secretKeyRef:
              name: ex-db-prod
              key: DB
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ex-db-prod
              key: PASSWORD
        - name: PORT_DB
          valueFrom:
            secretKeyRef:
              name: ex-db-prod
              key: PORT_DB
        - name: SERVER
          valueFrom:
            secretKeyRef:
              name: ex-db-prod
              key: SERVER
        - name: USER_DB
          valueFrom:
            secretKeyRef:
              name: ex-db-prod
              key: USER_DB
        - name: NODE_ENV
          value: PRODUCTION
        ports:
        - containerPort: 8080
      # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
      # project, the region of your Cloud SQL instance and the name
      # of your Cloud SQL instance. The format is
      # $PROJECT:$REGION:$INSTANCE
      # [START proxy_container]
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy", "-instances=centering-line-248621:us-central1:example-cloud-sql-dbe28180-prod=tcp:5432",
          "-ip_address_types=PRIVATE"]
                  #"-credential_file=/secrets/cloudsql/credentials.json"]
        # [START cloudsql_security_context]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        # [END cloudsql_security_context]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
      # [END proxy_container]
    # [START volumes]
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: ex-db-prod
    # [END volumes]

```

**Comment by kurtisvg** [comment]
I'm unable to replicate, but I suspect it's due to this section:
```yaml
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy", "-instances=centering-line-248621:us-central1:example-cloud-sql-dbe28180-prod=tcp:5432",
          "-ip_address_types=PRIVATE"]
```

What are you using for account credentials? If you provide a service account, does it still have this problem?
