### ISSUE TITLE
Inconsistent (broken) examples

### ISSUE THREAD

**Issue by warent** [GoogleCloudPlatform/cloudsql-proxy#404]
## Description
https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine
Documentation says to create the following secret:
```
kubectl create secret generic <YOUR-DB-SECRET> \
  --from-literal=db_user=<YOUR-DATABASE-USER> \
  --from-literal=db_password=<YOUR-DATABASE-PASSWORD> \
  --from-literal=db_name=<YOUR-DATABASE-NAME>
```

Later it shows a "Complete example configuration file":
https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#run_the_cloud_sql_proxy_as_a_sidecar
```yaml
    spec:
      serviceAccountName: <YOUR-KSA-NAME>
      containers:
      - name: <YOUR-APPLICATION-NAME>
        # ... other container configuration
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: database
```

Key names between secrets are different.

## Solution
The example should show what was originally generated.

```yaml
    spec:
      serviceAccountName: <YOUR-KSA-NAME>
      containers:
      - name: <YOUR-APPLICATION-NAME>
        # ... other container configuration
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: db_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: <YOUR-DB-SECRET>
              key: db_name
```

Also worth noting is that it is kind of a foot gun to have DB_PASS be the environment variable passed in to the container, and db_password be the secret key. Some people will probably try to type db_pass as the key and wonder why it isn't working (i.e. that's what I did)
