### ISSUE TITLE
Error when attempting to deploy with Workload Identity

### ISSUE THREAD

**Issue by thebigredgeek** [GoogleCloudPlatform/cloudsql-proxy#407]
## Bug Description

Following the latest instructions [here](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#proxy-with-workload-identity), I am left with a pod that fails to start with the following log output:

```
2020/06/22 21:13:09 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2020/06/22 21:13:09 errors parsing config:
	googleapi: Error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
More details:
Reason: authError, Message: Invalid Credentials
```

## Example code (or command)

Deployment yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - name: api
        image: api
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-connection-info
              key: host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-connection-info
              key: database
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-connection-info
              key: url
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-connection-info
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-connection-info
              key: password
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=keybox-281016:us-central1:development=tcp:5432"
        # securityContext:
        #   # The default Cloud SQL proxy image runs as the
        #   # "nonroot" user and group (uid: 65532) by default.
        #   runAsNonRoot: true
```

## How to reproduce

  1. Follow the instructions mentioned above

## Environment

1. OS type and version: Mac OS 10.15.4
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.17

**Comment by kurtisvg** [comment]
@thebigredgeek Can you confirm that you've correctly [enabled Workload Identity on your cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_on_existing_cluster)? If using an existing cluster you need to enabled it and [migrate your workloads](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#migrate_workloads_to).

**Comment by thebigredgeek** [comment]
Yes, I enabled it when I created the cluster.

<img width="431" alt="Screen Shot 2020-06-23 at 9 08 22 AM" src="https://user-images.githubusercontent.com/2799276/85414035-38408980-b531-11ea-88b8-6ad660e9c974.png">
](url)

**Comment by kaaloo** [comment]
Thanks for posting this @thebigredgeek.  I had a running cluster that I had setup maybe two weeks ago with Workload Identity for the CloudSQL Proxy but I tore it down yesterday to test some changes in our provisioning scripts and I've been experiencing the same issue since.  I also had trouble initially but it finally worked when I added this iam policy binding.  However, maybe that was a fluke.  In any case that "workaround" is no longer working.

```
gcloud projects add-iam-policy-binding ${PROJECT_ID} \
  --role roles/cloudsql.client \
  --member "serviceAccount:${PROJECT_ID}@${PROJECT_ID}.iam.gserviceaccount.com"
```

**Comment by thebigredgeek** [comment]
thanks @kaaloo !  I'd try this, but I want to make sure to stick to documented pathways for now.  I'm guessing there is a solution here, perhaps the docs are out of date?

**Comment by kurtisvg** [comment]
I'm unable to reproduce, so any additional information here would be helpful. I created a new GKE cluster (release channel - `1.16.8-gke.15`) w/ Workload Identity enabled. 

1. I created a KSA:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-proxy-sa
```

2. I bound it to an existing GSA:
```yaml
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$MY_PROJECT.svc.id.goog[default/my-proxy-sa]" \
  $MY_GSA@$MY_PROJECT.iam.gserviceaccount.com
```

3. I annotated my service account:
```yaml
kubectl annotate serviceaccount \
   my-proxy-sa \
   iam.gke.io/gcp-service-account=$MY_GSA@$MY_PROJECT.iam.gserviceaccount.com
```

4. Finally, I deployed an application:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabs-vs-spaces
spec:
  selector:
    matchLabels:
      app: tabs-vs-spaces
  template:
    metadata:
      labels:
        app: tabs-vs-spaces
    spec:
      serviceAccountName: my-proxy-sa
      containers:
      - name: tabs-vs-spaces
        image: $MY_IMAGE
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: us.gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=$MY_CONNECTION_NAME=tcp:5432"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
```

The logs from my sidecar show the proxy operating successfully.
