### ISSUE TITLE
Django Application Fails to Connect to Cloud SQL Proxy in Docker

### ISSUE THREAD

**Issue by jlibermann** [GoogleCloudPlatform/cloudsql-proxy#445]
## Bug Description

I'm trying to connect to my `cloudsql` database in Docker via the cloud proxy, but Django keeps throwing a `connectionerror.` 
## Example code (or command)
`docker-compose.yml`:
```
version: '3.8'

services:
    web:
        build: .
        depends_on:
            - tom_postgres_db
        command: python3 manage.py runserver 0.0.0.0:8080
        volumes:
            - .:/app
        ports:
        - 8080:8000
        - 8000:8000
        env_file:
        - .env
    tom_postgres_db:
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        ports:
            - 5432:5432
        command: ./cloud_sql_proxy -instances=${INSTANCE_CONNECTION_NAME}=tcp:0.0.0.0:5432 -credential_file=/config
        volumes:
        - ${GOOGLE_APPLICATION_CREDENTIALS}:/config
        restart: always
```
`.env`:

```
DEBUG=1
DJANGO_SETTINGS_MODULE=my-settings
SECRET_KEY=my-secret-key
DJANGO_HOST=127.0.0.1
GOOGLE_APPLICATION_CREDENTIALS=path-to-credentials
INSTANCE_CONNECTION_NAME=my-connection-name
SQL_ENGINE=django.db.backends.postgresql
SQL_DATABASE=my-db-name
SQL_USER=my-db-user
SQL_PASSWORD=my-db-pw
SQL_PORT=5432

```
## Stacktrace
```
django.db.utils.OperationalError: could not connect to server: Connection timed out
 	Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
```

## How to reproduce

  1. Run `docker-compose up` from project root.
  2. See error.

## Environment

1. OS type and version: Ubuntu 20.04
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.16
