### ISSUE TITLE
oauth2: cannot fetch token

### ISSUE THREAD

**Issue by sneko** [GoogleCloudPlatform/cloudsql-proxy#481]
Hi,

It's the same issue than https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/91 but it has been locked without any specific "tips" to solve this.

That's maybe linked to this answer https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/91#issuecomment-304074279 from @Carrotman42 ?

Indeed, in our case we have : 
1. a SQL cluster in US
2. a Kubernetes (GKE) cluster in US
3. some developers in Europe

- (1) and (2) works perfectly through the VPC network and we never had any similar issue
- but some developers in Europe tries to use the SQL proxy to debug the database when needed, but they face the following error randomly (and that's really really frequent): 
```
sqlproxy_1  | 2020/09/24 14:38:13 using credential file for authentication; email=XXXXXXXXX.iam.gserviceaccount.com
sqlproxy_1  | 2020/09/24 14:38:23 errors parsing config:
sqlproxy_1  |   Get https://www.googleapis.com/sql/v1beta4/projects/YYYYYYYYYYYY/instances/ZZZZZZZZZZZZZZZZZZ?alt=json&prettyPrint=false: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: dial tcp: lookup oauth2.googleapis.com on 127.0.0.11:53: read udp 127.0.0.1:53752->127.0.0.11:53: i/o timeout
mysql_sqlproxy_1 exited with code 1
```

Do you know what could be the cause? Note that we are not in the same building, that's the same when trying to reach out from home...

We tried with multiple versions including last ones like:
- gcr.io/cloudsql-docker/gce-proxy:1.16
- gcr.io/cloudsql-docker/gce-proxy:1.18.0

Thank you,

**Comment by Carrotman42** [comment]
Looks different than #91 because the error in this case talks about a
failure to connect to a DNS server to resolve oauth2.googleapis.com, as per
this portion of the error message:

> lookup oauth2.googleapis.com on 127.0.0.11:53

What is your DNS server on 127.0.0.11? Is it internal to your business?
Does it transiently have problems? Can you explain more about your DNS
setup, and check logs there to correlate timestamps?

**Comment by sneko** [comment]
Thanks @Carrotman42 for the answer.

I simply using a Docker compose like that:
```
#
# To use when another container needs the proxy (to be in the same network)
#

# export INSTANCE_ID=...
# export SERVICE_ACCOUNT_PATH=$(pwd)/.../service-account-XXXXX.json

version: '3.7'

services:
  sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.18.0
    command:
      /cloud_sql_proxy -ip_address_types=PUBLIC -instances=${INSTANCE_ID}=tcp:0.0.0.0:3306 -credential_file=/secrets/cloudsql/credentials.json
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ${SERVICE_ACCOUNT_PATH}:/secrets/cloudsql/credentials.json
    restart: on-failure

  adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 8080:8080
```

Note that `adminer` is just a UI tool for MySQL, but it also fails without it (logical since not related 👍 )
