### ISSUE TITLE
Connection refused using HPA when scale down

### ISSUE THREAD

**Issue by ALTELMA** [GoogleCloudPlatform/cloudsql-proxy#535]
## Question
I try to config the application to not receive traffic from proxy service with preStop and Readiness probe

```
readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
lifecycle:
            preStop:
              exec:
                command: ["sleep", "120"]
```

Then I was created an HPA config to scale up/down pod when having a lot of traffic, but I got a problem when scaling down because the container app cannot connect to the SQL proxy container. It returns *Connection refused*
