### ISSUE TITLE
cloudsql-proxy keeps restarting connections

### ISSUE THREAD

**Issue by aryan9600** [GoogleCloudPlatform/cloudsql-proxy#539]
## Bug Description

I have a dokcerized Django application and a Postgres server running on my CloudSQL instance. Everything works fine, and there are really no issues with the functionality, except for the fact that it seems like cloudsql-proxy keeps closing and opening new connections every 5 seconds.

## Example code (or command)

```
version: '3.7'

services:
  web:
    build: .
    command: bash -c "cd /code && python manage.py migrate --noinput && gunicorn project.wsgi:application
    volumes:
      - .:/code
    depends_on:
      - cloud_sql_proxy
  cloud_sql_proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command: /cloud_sql_proxy -instances=project_id:asia-east2:instance_name=tcp:0.0.0.
    volumes:
      - ./postgres-service-account.json:/config
    ports:
      - 5432:5432
```

## Stacktrace
```
cloud_sql_proxy_1  | 2020/11/12 17:10:56 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:10:57 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:02 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:02 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:07 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:07 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:12 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:12 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:17 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:17 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:23 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:23 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:28 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:28 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:33 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:33 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:38 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:38 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:44 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:44 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:49 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:49 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:54 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:54 New connection for "carbon-helix-273210:asia-east2:enigma"
cloud_sql_proxy_1  | 2020/11/12 17:11:59 Client closed local connection on 172.30.0.3:5432
cloud_sql_proxy_1  | 2020/11/12 17:11:59 New connection for "carbon-helix-273210:asia-east2:enigma"
```

## How to reproduce

  1. Prepare a docker-compose.yml file with all the necessary config
  2. Run `docker-compose up --build`
  3. Watch the logs

## Environment

1. OS type and version: docker-compose on Ubuntu 18.04
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.16
