### ISSUE TITLE
1.20.1 image crashes with: errors parsing config: exec: "gcloud": executable file not found in $PATH

### ISSUE THREAD

**Issue by mlazowik** [GoogleCloudPlatform/cloudsql-proxy#655]
## Bug Description

Our testing GKE cluster just pulled in the `gcr.io/cloudsql-docker/gce-proxy:1.20.1-alpine` image (we see the same problem with the `buster` variant), and all deployments are failing with:
```
2021/03/04 23:22:07 errors parsing config:
Get "https://sqladmin.googleapis.com/sql/v1beta4/projects/<project id>/instances/<instance>?alt=json&prettyPrint=false": exec: "gcloud": executable file not found in $PATH 
```

## Example code (or command)
Auth via workload identity.

```yaml
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.20.1-alpine
        command:
        - "/cloud_sql_proxy"
        # If connecting from a VPC-native GKE cluster, you can use the
        # following flag to have the proxy connect over private IP
        - "-ip_address_types=PRIVATE"
        # Replace DB_PORT with the port the proxy should listen on
        # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
        - "-instances=<project>:<region>:<name>=tcp:5432"
        securityContext:
          # The default Cloud SQL proxy image is based on distroless, which
          # runs as the "nonroot" user (uid: 65534) by default.
          runAsNonRoot: true
```

## Environment

1. OS type and version: GKE `1.18.15-gke.1102` with `cos_containerd`
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): `1.20.1`

## Possibly related

* #649
