### ISSUE TITLE
IAM authentication via Workload Identity not working

### ISSUE THREAD

**Issue by hazcod** [GoogleCloudPlatform/cloudsql-proxy#738]
## Bug Description

Hi, I am trying to authenticate to my postgresql 13 instance using the cloudsql-proxy and workload identity.
I've done following things:
- set `cloudsql.iam_authentication=on` flag on CloudSQL
- create user `dev-worker@PROJECT_ID.iam        CLOUD_IAM_SERVICE_ACCOUNT`  and checked with `sql users --list`
- check the IAM policy binding
```
shell
% gcloud --project="xxx" iam service-accounts get-iam-policy dev-worker@xxx.iam.gserviceaccount.com
bindings:
- members:
  - serviceAccount:xxx.svc.id.goog[dev-worker/dev-worker]
  role: roles/iam.workloadIdentityUser
etag: BwXAT81sc0w=
version: 1
```
- added applicable roles to the Pod SA
```shell
% gcloud projects get-iam-policy "xxx"  \
--flatten="bindings[].members" \
--format='table(bindings.role)' \
--filter="bindings.members:dev-worker@xxx.iam.gserviceaccount.com"
ROLE
roles/cloudkms.cryptoKeyEncrypterDecrypter
roles/cloudsql.client
roles/cloudsql.instanceUser
roles/pubsub.publisher
roles/pubsub.subscriber
```

My cloudsql-proxy sidecar:
```yaml
 imagePullPolicy: Always
        image: eu.gcr.io/cloudsql-docker/gce-proxy:1.21.0
        name: cloudsql-proxy

        command:
        - '/cloud_sql_proxy'
        - '-enable_iam_login'
        - '-instances=xxx:europe-west1:mydb=tcp:3126'

        resources:
          requests:
            cpu: 0.5
            memory: 0.5Gi
          limits:
            cpu: 0.5
            memory: 0.5Gi

        securityContext:
          readOnlyRootFilesystem: true
          privileged: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: [all]
          seccompProfile:
            type: RuntimeDefault
```

## Stacktrace
```
Get "https://sqladmin.googleapis.com/sql/v1beta4/projects/xxx/instances/europe-west1~mydb?alt=json&prettyPrint=false": compute: Received 403 `Unable to generate access token; IAM returned 403 Forbidden: The caller does not have permission
This error could be caused by a missing IAM policy binding on the target IAM service account.
For more information, refer to the Workload Identity documentation: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#creating_a_relationship_between_ksas_and_gsas
```

## Environment

1. OS type and version: GKE AutoPilot
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): eu.gcr.io/cloudsql-docker/gce-proxy:1.21.0
