### ISSUE TITLE
cannot fetch token: Post https://accounts.google.com/o/oauth2/token: x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by norbert-yoimo** [GoogleCloudPlatform/cloudsql-proxy#78]
I'm trying to connect to a postgresql cloudsql instance, from a kubernetes pod, but when I try to establish a connection with `psql -h 127.0.0.1`, I get:

```
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

Looking at the logs of the cloudsql pod, I see:

```
2017/04/04 13:15:53 New connection for "myproject-157612:europe-west1-c:myproject"
2017/04/04 13:15:53 couldn't connect to "myproject-157612:europe-west1-c:myproject": Post https://www.googleapis.com/sql/v1beta4/projects/myproject-157612/instances/myproject/createEphemeral?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: x509: failed to load system roots and no roots provided
```

I'm using cloudsqlproxy 1.07, with the following deployment spec:

```
- image: gcr.io/cloudsql-docker/gce-proxy:1.07
    name: cloudsql
    command: ["/cloud_sql_proxy", "-dir=/cloudsql", "-credential_file=/secret/cloud-sql.json", "-instances=myproject-157612:europe-west1-c:myproject=tcp:5432"]
    volumeMounts:
        - name: cloudsql
          mountPath: /cloudsql
        - name: sql-proxy-secret
          mountPath: /secret/
```

Am I supposed to mount some SSL certificates inside the cloud sql pod?
