### ISSUE TITLE
Error during SIGTERM shutdown: 1 active connections still exist after waiting for 0s

### ISSUE THREAD

**Issue by Emixam23-FCMS** [GoogleCloudPlatform/cloudsql-proxy#799]
## Situation

Hello, I saw many thread regarding this issue while using sqlproxy as side car in Kubernetes however, it seems that the "issue" is still here even after a couple of years (based on github issue's dates).
  
## Question

What I would like to know is if there is a real proper solution to handle container termination (and avoid any critical output in GKE workload logs)?

## Additional Context

I would like to add that this critical log (SIGTERM related) `Error during SIGTERM shutdown: 1 active connections still exist after waiting for 0s` is happening on **gcr.io/cloudsql-docker/gce-proxy:1.22.0** when my autoscaler downscale my deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myApp
  namespace: foobarr
  labels:
    ...
spec:
  replicas: ...
  selector:
    matchLabels:
      ...
  template:
    metadata:
      labels:
        ...
    spec:
      containers:
        - name: sqlproxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
          command: ["/cloud_sql_proxy",
                    "-instances={{ .Values.pgDbInstance }}",
                    "-verbose=false",
                    "-log_debug_stdout=true"]
          resources:
            requests:
              cpu: 400m
        - name: myApp
          image: myAppImage
          env: ...
```

Thanks for any relevant feedback :)
