### ISSUE TITLE
CloudSQL Proxy 175% slower than direct connection

### ISSUE THREAD

**Issue by mpskovvang** [GoogleCloudPlatform/cloudsql-proxy#87]
Is the proxy expected to be 175% slower than a direct connection?

Every hour I'm also experiencing some spikes. The first query takes up to 1 second. Could it be some kind of reauthentication?

In my small test, the first query (which creates the connection) takes 5ms without proxy and >15ms with proxy.

Can I do any configuration to reduce the latency?

**Comment by Carrotman42** [comment]
Please try using connection pooling. It will drastically decrease the
amount of time it takes to execute queries due to a decrease in the total
number of "new connection handshakes". You will much shorter latency
with/without the proxy using a connection pool.

Also, the first connection via the Proxy per hour will be a little longer,
as we have to request a certificate from our backend which only is valid
for 1 hour. That certificate is cached for that whole hour for all other
connections via the proxy (regardless of connection pooling).

In any case, please share the exact setup you used to get these numbers.
The Proxy is expected to have some overhead, but the numbers you quoted are
higher than I'd expect.

**Comment by Carrotman42** [comment]
I read your post a little more closely and it does appear that you're
hitting some spikes during cert refresh, or at least it's part of your
problem. The Proxy code could easily be smarter about refreshing it's
certificate: instead of waiting for the hour to be up and blocking new
connections until a new certificate is retrieved, it could ask for a new
cert 5 minutes beforehand (in the background) so that the new cert can be
swapped in without any latency increase.

If the spike in latency is not your only problem, would you mind forking
off a new Issue to track that sort of feature request?

**Comment by mpskovvang** [comment]
Thanks for your suggestion @Carrotman42 but unfortunately PHP does not support connection pooling unless using the ODBC driver which I guess is more inefficient.

The spike every hour is my primary problem as it is triggering my monitoring alerts. Maybe these details might be helpful:
The spike happens for all proxy containers every hour blocking 1 or more queries for ~1 second. The query doesn't get catch by the MySQL slow log.

Note: The comparison might not be truly fair as I was using a non-secure direct connection. The general overhead could be caused by the encryption? By removing the first query from the result makes the difference smaller: 22ms vs 31ms for 29 simple select queries.

**Comment by rigalrock** [comment]
In my case cloud sql proxy is way too slow as compare to direct connection using ip whitelisting .
I wrote a small api  where I was starting a transaction and committing it . I deployed this app first on Google Container Engine and was connecting to Cloud Sql using proxy , second I deployed it on Google Compute Engine and was connecting to Cloud sql via ip whitelisting . Below are the results 
+-----------------+--------------------+-----------------+-----------------+
| App Deployed on | Number of Requests | 99th percentile | Connecting Via  |
+-----------------+--------------------+-----------------+-----------------+
| GKE                      |              20140          | 113ms                  | Cloud Sql Proxy  |
| GCE                      |              20895         | 13ms                    | IP whitelisting     |
+-----------------+--------------------+-----------------+-----------------+
I am using hibernate to interact with mysql and using below config to connect to mysql for both deployments : 
```
database:
  driverClass: com.mysql.jdbc.Driver

  # the JDBC URL
  url: jdbc:mysql://DB_IP/DB_NAME?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s


  # the SQL query to run when validating a connection's liveness
  validationQuery: "SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 42
  properties:
      charSet: UTF-8
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: validate
      hibernate.session.events.log: false

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  maxConnectionAge : 10s
  checkConnectionOnBorrow: true
```
